### PR TITLE
C Bindings

### PR DESCRIPTION
**Pull request by InfinityMod**
I created some C bindings to watchexec and updated the project to also be compiled as a dynamic library. This could be useful if the function of watchexec should be integrated into other programming languages e.g. for creating some synchronizing program.

The "watch_test.cpp" application integrates watchexec in a simple example and shows the changed files including the cookie, the filepath, the action and the timestamp of the changes.

Please let me know, what you think about this feature.

David

### CODE REVIEW

**Comment by passcod** [comment]
Um, wow, alright. This is really cool, and thanks for providing a complete implementation!

However, I'm not sure this would be in scope. I need @mattgreen's opinion here.

If this is merged, then I expect that like the library interface, semver would not break and hold for this aspect, i.e. breaking changes in this interface could be introduced as minors.

If it's not in scope, one possibility that I _think_ would work (but you'd know more) is to make the bindings a third-party crate that consume the Rust lib interface instead of being directly integrated.

**Comment by passcod** [comment]
> I also think that semver should not break and even if, a introduction of the changes as minors would work.

I'm sorry, I should have expressed this better.

The initial merge of such a feature, or of the more minimal set of changes you outlined would be a minor change... but so would every change to this feature thereafter, too.

The rationale here is that watchexec is a command line tool and the interface considered for semver purposes is the command line interface. The Rust library interface (and an hypothetical C library interface) _may break compatibility at any release level_. The recommendation for library consumers is to pin to a version.

---

On further review, I also see that the purpose of the bindings mostly skip the child running functionality? Do I have that right? And in that case, could you implement the bindings directly on top of the underlying Notify rather than going over watchexec?

At the very least, Notify is versioned as a library (I'm the author). Also I would very much welcome a C interface.

If there is a particular reason why not: I do feel a lot more comfortable merging the minimal set of changes as you describe above rather than the whole bindings, so if you alter this PR for just that set, it would work out.

**Comment by InfinityMod** [comment]
> On further review, I also see that the purpose of the bindings mostly skip the child running functionality? Do I have that right? 

Yes that's correct, because file changes are directly passed thought to the C (C++) application, no child processes need to be launched.

> And in that case, could you implement the bindings directly on top of the underlying Notify rather than going over watchexec?

I currently choose watchexec to be extended because it offers simple commands for additional file-filtering by .gitignore or regex and also other features that are implemented, useful and already usable without any additional implementation effort. 
As you mentioned the core part of watchexec relies on your implementation notify which is really impressive. Thank's for doing this bunch of implementation work! 

I think c bindings for notify  are also possible to implement, but it needs to be considered if some predefined subroutines (as they are already implemented into watchexec) should be ported to C or even the whole public interface of notify. The second option would make a lot more work, but also give some additional flexibility for C users (and bindings for other programming languages).

> If there is a particular reason why not: I do feel a lot more comfortable merging the minimal set of changes as you describe above rather than the whole bindings, so if you alter this PR for just that set, it would work out.

I made a new pull request (#104) which covers these functionalities now. I also set up the third party crate, you can reach it at: [https://github.com/InfinityMod/watchexec_c](https://github.com/InfinityMod/watchexec_c).

**Comment by mattgreen** [comment]
I'm a little late.

In the long term, I think it makes more sense to abstract out watchexec itself into `libwatchexec` and then consume that from various frontends, including the existing CLI app. This is a big change, however.

When I originally built watchexec I tried to make it as modular as possible by hooking most of the components together in `main()`; this was somewhat successful. Nowadays there may be better abstractions/concepts that might take their place. Clients of `libwatchexec` could then build file watchers that do exactly what they want by configuring ignore functionality, debouncing, and handling file update notifications.

I resisted this urge when I was making it because I hate software for it's own sake. It might be a better time to consider it, however!

**Comment by passcod** [comment]
Thanks for popping in! I think that's the direction it's moving towards, anyway, but I'm glad to have your words on it :)

I'll keep libraryizing things as I work on it, and somewhere down the track I hope it will feel ready enough to split into two crates :package: :package: (a ways away still, I think, as everything is a bit too tightly coupled, if modularised... the `process` module especially).

**Pull request closed without merging**
