### PR TITLE
Fix child env overflow

### PR DESCRIPTION
**Pull request by qguv**
Addresses #78 by adding two new command-line options: `--no-meta` and `--no-environment`.

`--no-meta`: Ignore metadata changes. I found that running `make` as the child process in a directory with a large repository causes file metadata changes for tons of files. The resulting very large WATCHEXEC_*_PATH environment variable values quickly exhaust the [128k buffer](https://wiki.debian.org/CommonErrorMessages/ArgumentListTooLong) used by Linux to pass environment to a child process. Ignoring such changes produces much smaller lists of modified files in cases like this, avoiding the overflow.

`--no-environment`: Do not set WATCHEXEC_*_PATH environment variables for the child process. This is a more general solution for projects with even more files. If the environment variables are never generated in the first place, at least we know we're not contributing to the overflow. A massive parent environment or argument list could still push it over the limit though.

### CODE REVIEW

**Comment by passcod** [comment]
Would it be possible to estimate the size of the argument/env for the child command and display a warning referencing these flags and/or truncate the envvar to fit?

**Comment by passcod** [comment]
[versioning note: this is a feature add but not considered an api breaking change (due to the builder)]

**Comment by qguv** [comment]
Good idea. To avoid breaking the API maybe I could just print a better message before exiting in cases where it would/does overflow the buffer? It doesn't feel right to pass some, but not all, changed files to the child, especially if the user doesn't expect it and the child has no way to distinguish between truncated and untruncated cases.

**Comment by passcod** [comment]
That sounds good. I was thinking of adding a `WATCHEXEC_CHANGES_TRUNCATED` but that would still be a breaking change, so an "informative" crash is likely best at this point

**Comment by qguv** [comment]
@passcod Done!

**Comment by qguv** [comment]
Hi all, it would be lovely to have this released. Anything I can do to help?

**Comment by passcod** [comment]
I'll get to it this week, if you're happy to wait a few more days (at most)

**Pull request merged**
