### PR TITLE
feat: Add arm-unknown-linux-gnueabihf target

### PR DESCRIPTION
**Pull request by jaysonsantos**
I've added it to the ignorable errors so it does not break your current flow in case of problems

### CODE REVIEW

**Comment by passcod** [comment]
I'm going go close this not because I don't want it but because I'm about to switch us over to Github Actions, and I'll make that a target platform there.

**Comment by jaysonsantos** [comment]
@passcod sure, let me know if you would like help there I've just implemented it here https://github.com/jaysonsantos/mambembe

**Comment by passcod** [comment]
It's all good, I got cargo-watch going already and that had pretty much the same setup.

**Comment by passcod** [comment]
Done in 1.15.0

**Pull request closed without merging**
