### PR TITLE
Add --changes-only option to only print path change information.

### PR DESCRIPTION
**Pull request by nindoja**
Implements the feature requested in https://github.com/watchexec/watchexec/issues/138

### CODE REVIEW

**Comment by passcod** [comment]
Awesome, thank you!

**Review by passcod — APPROVED** [review]

**Comment by nindoja** [comment]
@passcod thanks for the prompt review! I realized I didn't make changes to the docs to cover the new option. I'll put a new PR out for that.

As a related aside, what's the process for getting a new release done? I'd like to do a PR for `cargo-watch` to make use of this feature, but will need a new release before I can get that PR done.

**Comment by passcod** [comment]
I'll do a release this weekend.

That said, you can develop the cargo-watch PR by replacing the dependency with a `git=` one, and switch it back once I release.

**Comment by passcod** [comment]
by the way, don't do this:

> I realized I didn't make changes to the docs to cover the new option. I'll put a new PR out for that.

I've got it.

**Comment by passcod** [comment]
Released (a bit differently) in 1.15.0

**Pull request merged**
