### PR TITLE
Configuration file

### PR DESCRIPTION
**Pull request by passcod**
**Feedback wanted!**

First draft of format:

```kdl
command "hello-world" {
	run shell="bash" "echo 'hello world' > /tmp/test.txt"
	// run "echo" "hello world"
	// run shell="bash" "echo" "hello world" // error!

	process-group true

	debounce (ms)50
	postpone true

	on-action {
		when-idle {
			print "Once more..."
			start
		}

		when-busy restart
		// when-busy {
		// 	signal "KILL"
		// 	restart
		// }
	}

	environment {
		set SET_VAR="value"
		set MULTIPLE="vars" ON="one line"
		unset "UNSET_VAR"
		path-changes false
	}

	notifications {
		on-start false
		on-finish default=false {
			on-error {
				body "That didn't work"
			}

			on-signal {
				body "Who did this?!"
			}

			title "Whoopsie"
		}
	}

	clear {
		on-start method="reset"
	}

	ignores {
		vcs "git"
		global false
	}

	filters engine="tagged" {
		path "*=" "hello.*"
		file-event-kind "*=" "Create(*)"
		file-type "!=" "dir"
	}
}

command "and-another-thing" {
	with-profile "custom"

	hook on="exit" match="success" {
		subcommand name="hello-world" {
			send-event /* (empty) */
		}
	}

	hook on="exit" regex="(error|signal)\((\d+)\)" {
		quit code="$1"
	}
}

profile "default" {
	environment {
		set ALWAYS="present"
	}
}

profile "custom" {
	environment {
		set ALWAYS="custom"
	}
}
```

Syntax is from [KDL](https://kdl.dev).

Invocations:

- With explicit config file:
	  ```
	  $ watchexec -C config.kdl :hello-world
	  ```
- With multiple explicit files (merged):
	  ```
	  $ watchexec -C config1.kdl -C config2.kdl :hello-world
	  ```
- With default project-local config at `Watchexec.kdl`:
	  ```
	  $ watchexec :hello-world
	  ```
- With default global config at `~/config/watchexec/config.kdl`:
	  ```
	  $ watchexec :hello-world
	  ```
- Calling a configured command with additional options:
	  ```
	  $ watchexec -vvv :hello-world
	  ```
- Calling a configured command with additional arguments:
	  ```
	  $ watchexec :hello-world args args
	  ```
- Calling a configured command that doesn't have a `run`:
	  ```
	  $ watchexec :hello-world command to run
	  ```
- Just using config for defaults:
	  ```
	  $ watchexec do something
	  ```
- With a different profile:
	  ```
	  $ watchexec -P custom do something
	  ```

### CODE REVIEW

**Comment by alsuren** [comment]
> Feedback wanted!

I'm not sure how useful this is, but here is a brain dump of things that came to mind.

Gut reaction on the format: it feels powerful. This is not always appropriate though ([rule of least power](https://en.wikipedia.org/wiki/Rule_of_least_power) and all that).

I think I was expecting something very limited, with a low impedance mismatch between command line flags and the config file format, when expressing things with command line flags becomes too awkward or repetitive. 

If feels like this watchexec config format is looking to replace Makefile in my workflow or something? This feels like a game-changer.

If it is entering this space, is it worth looking into the formats used by other tools in the build space?

Cargo make:
https://github.com/sagiegurari/cargo-make

Ninja build:
https://ninja-build.org/manual.html#_syntax_example

The Bazel/Buck/Pants family of buildsystems (I think these use a subset of python as their config file format, which definitely feels like overkill in its power and complexity):
https://docs.bazel.build/versions/5.0.0/tutorial/cpp.html#specify-multiple-build-targets
https://buck.build/learning/tutorial.html
https://www.pantsbuild.org/docs/targets#build-files

Ant:
https://ant.apache.org/manual/index.html

Grunt (uses javascript):
https://gruntjs.com/sample-gruntfile

Github Actions:
https://docs.github.com/en/actions/quickstart#creating-your-first-workflow

There are probably a bunch of other buildsystems that are more similar to watchexec, that I've not thought of.

I'm not sure what I'm trying to achieve by looking at these things. Initially I thought "try not to miss any features that you might want", but many of these are too powerful and complicated.

Github Actions is probably the thing that I'd be most likely to use as inspiration, if I was building this feature. Yaml is capable of expressing everything that you need, in a format that you can describe using jsonschema and get completion and intelisense for in your IDE (https://github.com/redhat-developer/vscode-yaml#associating-a-schema-in-the-yaml-file). Yaml is a bit horrible if you've never used it before, but it seems to be used for everything in DevOps land, and the fact that you only need to learn one syntax for a whole suite of tools is pretty powerful. Definitely consider yaml and jsonc as alternative file formats.

**Comment by passcod** [comment]
Thanks for the feedback!

One thing I want to write down my thoughts on:

> If feels like this watchexec config format is looking to replace Makefile in my workflow or something? This feels like a game-changer.

_Explicitly not!_ But it can be a bit subtle.

All these things are build systems / task runners, except github actions, which I'll mention later. (Given this is likely to extend to cargo-watch in some form, I'm also very conscious of efforts to get a task runner into cargo itself, and don't want to have more implementations in the same space!)

The watchexec config is intended to configure watches, command runners in the watchexec concept\*, and the relationship between these. It won't be appropriate for specifying exactly what needs to happen, dependency trees, transformations on source and binary, etc. It's also not great for running multiple-to-many logically-grouped commands sequentially or in parallel.

That said: down the line, watchexec *will* get logic like "restart X if Y does Z" because that's generally useful (and has been requested a bunch). But that's something that is very complicated to set up using command line flags! So this initial design was influenced a lot by wanting to support that in the longer term. 

A good comparison is indeed GitHub Actions: it's domain specific (CI, with many options dedicated to CI features, and... just three for running commands? I think), you don't generally want to have complex scripts in it (though you can) (calling `make package` in your GHAs is usually better than embedding the packaging script, yes even though that's not what I do), you're going to _call_ your build system from it.

Watchexec config will both call your build system _and_ be called by it. Think eg:

1. `npm install`, ran when `package.json` changes, postponed
2. `npm run build-dev`, ran when files change, but not `package.json` or the lock file, and/or when 1 completes successfully
3. `npm run start-server-dev`, started when 2 completes successfully, restarted when `build/server` changes, sent the `HUP` signal when `build/resources` changes.
4. `npm run start-dev`, starts the watchexec config that does 1–3

That builds up to something pretty powerful, but concerns are separated!

---

\* "command runners in the watchexec concept": specifically, watchexec is concerned with running the command, watching for its return, restarting it, providing its environment from what it knows, sending or handling signals during its lifecycle, etc.

**Comment by passcod** [comment]
Oh, to reiterate/make explicit:

> I think I was expecting something very limited, with a low impedance mismatch between command line flags and the config file format, when expressing things with command line flags becomes too awkward or repetitive.

There's a bunch of very old issues that are like "this is cool, and would be good to have, but would be hell to implement via CLI flags." That's more or less explicitly stated.

There's also features that could be useful, but don't _quite_ merit a dedicated option.

For example, multiple inter-related commands (hard), or being able to reset the screen rather than clear it (niche), or being able to disable recursion on one particular folder (hard and niche).

So the config quite naturally has this thought that it's not going to be 1:1 with the CLI, and might not even be strictly a superset (there may be things that only make sense as CLI flags).

I think if looking for one more comparison, look at "docker-compose" vs the CLI suite of docker commands.

**Comment by passcod** [comment]
Closing in favour of a new draft implementation soonish given lots has changed in the meantime

**Comment by tammersaleh** [comment]
got a link to that new draft implementation?

**Comment by passcod** [comment]
From a year ago? No longer. This fell on the wayside, but happy to get more ideas/feedback here or in the [discussions](https://github.com/watchexec/watchexec/discussions).

**Pull request closed without merging**
