### PR TITLE
Switch to gix-config because git-config is deprecated

### PR DESCRIPTION
**Pull request by david-a-perez**
All packages from the `gitoxide` have been renamed from `git-*` to `gix-*`. Additionally, this pull request updates from `git-config` v0.14.0 to `gix-config` v0.16.2

### CODE REVIEW

**Comment by passcod** [comment]
This project's MSRV policy is stable+5, i.e. as the current stable is 1.66, we support 1.61. gitoxide's current MSRV is 1.64, so any upgrade will have to wait until the current stable is 1.69

**Comment by roblperry** [comment]
Once it can be merged, this PR will address #503

**Comment by passcod** [comment]
Okay, due to this and another widely-used dependency breaking more recently, I'm ditching MSRV in #510. That will unblock this PR.

**Comment by Wulf** [comment]
Thanks Félix!

**Pull request merged**
